import psutil
result01=psutil.cpu_times()
result02=psutil.cpu_stats()
result03=psutil.cpu_freq()
result04=psutil.disk_partitions()
result05=psutil.net_io_counters(pernic=True)
result06=psutil.net_io_counters(pernic=False)
print(result05)
print("==========================")
print(result06)